### ISSUE TITLE
Vault Theme

### ISSUE THREAD

**Issue by nickfrescas** [javalent/second-window#26]
Would it be possible to have the second window apply the vault theme? Or at least a dark mode toggle?

**Comment by sigrunixia** [comment]
In my testing, second window is applying a dark mode theme in its notes. It will not apply a dark mode to its top status bar, because it's using a system window versus an Obsidian Window.

<img width="964" alt="image" src="https://github.com/javalent/second-window/assets/68425372/20b281ab-6f63-49c9-bc33-7f9b76857565">

If you are having issues with it not applying dark mode, there may be some conflicting CSS at play, but the plugin itself fully supports it on its own.
